export const Tags = [
    { label: "혼자", key: "ALONE" },
    { label: "친구와", key: "WITH_FRIEND" },
    { label: "연인과", key: " WITH_LOVER" },
    { label: "배우자와", key: "WITH_SPOUSE" },
    { label: "아이와", key: "WITH_CHILD" },
    { label: "부모님과", key: "WITH_PARENTS" },
    { label: "반려동물과", key: "WITH_PET" },
    { label: "맑음", key: "SUNNY" },
    { label: "비", key: "RAIN" },
    { label: "바람", key: "WINDY" },
    { label: "추움", key: "COLD" },
    { label: "더움", key: "HOT" },
    { label: "대중교통", key: "PUBLIC_TRANSPORT" },
    { label: "자동차", key: "CAR" },
    { label: "뚜벅이", key: "ON_FOOT" },
];