import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import SessionModalProvider from "@/SessionModalProvider";

export const metadata: Metadata = {
  title: "OLCO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <SessionModalProvider />
        </Providers>
      </body>
    </html>
  );
}